### ISSUE TITLE
vue invoke buefy  fail❌

### ISSUE THREAD

**Issue by chinanf-boy** [buefy/vue-cli-plugin-buefy#1]
``` sh
ERROR  Error: You must provide a `message` parameter
Error: You must provide a `message` parameter
```

0. `npm i -g @vue-cli`

1. `vue create my-project`

2. ` cd my-project` & `yarn add -D vue-cli-plugin-buefy`

3. `vue invoke buefy`
Error log

**Comment by anteriovieira** [comment]
Hi @chinanf-boy I'll complete the implementation soon.

**Comment by anteriovieira** [comment]
@chinanf-boy  install the version `v0.1.0` :smiley:
