### ISSUE TITLE
Vue 3 with typescript can't use Buefy

### ISSUE THREAD

**Issue by mavyfaby** [buefy/vue-cli-plugin-buefy#15]
I just add buefy to my Vue 3 project using:

```sh
$ vue add buefy
```

and then error happens:

![Screenshot from 2021-01-19 10-47-15](https://user-images.githubusercontent.com/51808724/104981786-42355700-5a44-11eb-9109-2ce0c7bf2b01.png)
Image 1.

The Image 1 states that Vue is not defined so I import it.

![Screenshot from 2021-01-19 10-48-08](https://user-images.githubusercontent.com/51808724/104981854-61cc7f80-5a44-11eb-84cd-509807b9cc7d.png)
Image 2.

The Image 2 states that the `use` methods is not defined in Vue.

I tried using it in `createApp` function and still doesn't work:

![Screenshot from 2021-01-19 10-48-40](https://user-images.githubusercontent.com/51808724/104981984-a48e5780-5a44-11eb-857c-3ccfa12b8b47.png)

What do I do?

**Comment by jtommy** [comment]
Buefy doesn't support Vue 3 at the moment

**Comment by grbrjlz** [comment]
is there still no support?

**Comment by lizziekarr** [comment]
Is support for Vue 3 on the roadmap?
