### ISSUE TITLE
Option to use Bulma sass rather than css

### ISSUE THREAD

**Issue by SharpSeeEr** [buefy/vue-cli-plugin-buefy#2]
It would be nice if there were an option to use Bulma by including the sass files in a custom sass/scss file.  I would base the custom sass file on the official [Bulma Customization](https://bulma.io/documentation/overview/customize/) docs.  I'd be happy to code this up and submit a pull request if it's something you are interested in.

**Comment by anteriovieira** [comment]
Hi @SharpSeeEr , yes, feel free to send us a pull request. I appreciate your contribution :smiley:
