### ISSUE TITLE
generator created .variables.scss rather than _variables.scss

### ISSUE THREAD

**Issue by HintikkaKimmo** [buefy/vue-cli-plugin-buefy#8]
I just tested this plugin with a new side project. Generator created .variable.scss which seems to break Vue cli Webpack configurations. Changing manually fixes the issue, but I curious on why/how this happens as the template would seem to have _variables.scss?

**Comment by anteriovieira** [comment]
Hi @HintikkaKimmo , thanks for reporting. 

I found the reason: [GeneratorAPI](https://github.com/vuejs/vue-cli/blob/05391b6e9e51917437d79c46721548dc7038993a/packages/%40vue/cli/lib/GeneratorAPI.js#L139)

**Comment by HintikkaKimmo** [comment]
Ah cool thanks @anteriovieira

**Comment by anteriovieira** [comment]
@HintikkaKimmo I'll think of a solution for this

**Comment by lewalkingdad** [comment]
@anteriovieira a quick solution would be to not pass the source as a a string but as an object or a function instead.

**Comment by SharpSeeEr** [comment]
Minimal reproduction steps for vue-cli bug report:

1. Create a new project: `vue create <projectname>` and choose to install support for SASS.
1. Install plugin: `vue add buefy` and select to add SCSS support.
1. The file located at
`src/assets/scss/.variables.scss` should be named 
`src/assets/scss/_variables.scss`

**Comment by SharpSeeEr** [comment]
They updated vue cli so that if a file is supposed to start with an underscore you essentially escape the underscore with another underscore:
`
_varialbes.scss -> .variables.scss
__variables.scss -> _variables.scss
`

**Comment by anteriovieira** [comment]
Thanks @SharpSeeEr
