### ISSUE TITLE
need to install `node-sass` and `sass-loader` when using rc5 cli

### ISSUE THREAD

**Issue by johnwebbcole** [buefy/vue-cli-plugin-buefy#9]
With vue-cli rc3 and below, using `vue add buefy` worked without any additional projects.  Creating a new project with rc5 and then running `vue add buefy` now requires you to add `node-sass` and `sass-loader` as dev dependencies.

```
npm i -D sass-loader node-sass
```

I'm not sure if the plugin should reference these or add them (or just make a note in the docs).

Thx!

**Comment by anteriovieira** [comment]
Hi @johnwebbcole we can add in the package as dependence when the sass option is passed.

**Comment by anteriovieira** [comment]
Fixed in version `v0.3.0` :smiley:
